export enum Subtype {
    Baby = 'Baby',
    Basic = 'Basic',
    Break = 'BREAK',
    EX = 'EX',
    GoldenrodGameCorner = 'Goldenrod Game Corner',
    GX = 'GX',
    Item = 'Item',
    Legend = 'LEGEND',
    LevelUp = 'Level-Up',
    Mega = 'MEGA',
    PokemonTool = 'Pokémon Tool',
    PokemonToolF = 'Pokémon Tool F',
    RapidStrike = 'Rapid Strike',
    Restored = 'Restored',
    RocketsSecretMachine = "Rocket's Secret Machine",
    SingleStrike = 'Single Strike',
    Special = 'Special',
    Stadium = 'Stadium',
    StageOne = 'Stage 1',
    StageTwo = 'Stage 2',
    Supporter = 'Supporter',
    TagTeam = 'TAG TEAM',
    TechnicalMachine = 'Technical Machine',
    V = 'V',
    VMax = 'VMAX',
}
